Simulating error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,4 +12,7 @@ jobs:
       - name: Run a sample github actions
 
         run: echo "This workflow is run successfully for this particular action"
+
+      - name: simulating error
+        run: echo "Error taking place"; exit 1
       
